from dataclasses import dataclass
from typing import Literal

PermissionType = Literal["menu", "action"]


@dataclass(frozen=True)
class PermissionDefinition:
    code: str
    name: str
    type: PermissionType
    description: str


ADMIN_ROLE_CODE = "admin"
ADMIN_ROLE_NAME = "管理员"
PERMISSION_MANAGE_SUPERUSER = "action:users:manage_superuser"

DEFAULT_PERMISSIONS: tuple[PermissionDefinition, ...] = (
    PermissionDefinition(
        code="menu:dashboard",
        name="首页菜单",
        type="menu",
        description="查看首页导航入口。",
    ),
    PermissionDefinition(
        code="menu:apps",
        name="应用中心菜单",
        type="menu",
        description="查看应用中心导航入口。",
    ),
    PermissionDefinition(
        code="menu:users",
        name="用户管理菜单",
        type="menu",
        description="查看用户管理导航入口。",
    ),
    PermissionDefinition(
        code="menu:roles",
        name="角色权限菜单",
        type="menu",
        description="查看角色权限导航入口。",
    ),
    PermissionDefinition(
        code="menu:departments",
        name="空间管理菜单",
        type="menu",
        description="查看空间管理导航入口。",
    ),
    PermissionDefinition(
        code="menu:audit",
        name="操作日志菜单",
        type="menu",
        description="查看操作日志导航入口。",
    ),
    PermissionDefinition(
        code="menu:dictionaries",
        name="配置字典菜单",
        type="menu",
        description="查看配置字典导航入口。",
    ),
    PermissionDefinition(
        code="menu:files",
        name="文件资源菜单",
        type="menu",
        description="查看文件资源导航入口。",
    ),
    PermissionDefinition(
        code="action:dashboard:read",
        name="查看首页",
        type="action",
        description="查看首页数据。",
    ),
    PermissionDefinition(
        code="action:apps:read",
        name="查看应用",
        type="action",
        description="查看应用中心数据。",
    ),
    PermissionDefinition(
        code="action:apps:create",
        name="创建应用",
        type="action",
        description="创建应用中心入口。",
    ),
    PermissionDefinition(
        code="action:apps:update",
        name="编辑应用",
        type="action",
        description="编辑应用中心入口。",
    ),
    PermissionDefinition(
        code="action:apps:manage_status",
        name="管理应用状态",
        type="action",
        description="启用或停用应用中心入口。",
    ),
    PermissionDefinition(
        code="action:users:read",
        name="查看用户",
        type="action",
        description="查看用户管理数据。",
    ),
    PermissionDefinition(
        code="action:users:create",
        name="创建用户",
        type="action",
        description="创建用户账号。",
    ),
    PermissionDefinition(
        code="action:users:update",
        name="编辑用户",
        type="action",
        description="编辑用户账号。",
    ),
    PermissionDefinition(
        code="action:users:update_roles",
        name="分配用户角色",
        type="action",
        description="更新用户已分配的角色。",
    ),
    PermissionDefinition(
        code="action:roles:read",
        name="查看角色",
        type="action",
        description="查看角色权限数据。",
    ),
    PermissionDefinition(
        code="action:roles:create",
        name="创建角色",
        type="action",
        description="创建自定义角色。",
    ),
    PermissionDefinition(
        code="action:roles:update",
        name="编辑角色",
        type="action",
        description="编辑自定义角色。",
    ),
    PermissionDefinition(
        code="action:roles:delete",
        name="删除角色",
        type="action",
        description="删除未分配用户的自定义角色。",
    ),
    PermissionDefinition(
        code="action:roles:update_permissions",
        name="配置角色权限",
        type="action",
        description="更新角色已分配的权限。",
    ),
    PermissionDefinition(
        code="action:departments:read",
        name="查看空间",
        type="action",
        description="查看空间管理数据。",
    ),
    PermissionDefinition(
        code="action:departments:create",
        name="创建空间",
        type="action",
        description="创建空间记录。",
    ),
    PermissionDefinition(
        code="action:departments:update",
        name="编辑空间",
        type="action",
        description="编辑空间记录。",
    ),
    PermissionDefinition(
        code="action:departments:delete",
        name="删除空间",
        type="action",
        description="删除没有子空间且未分配用户的空间。",
    ),
    PermissionDefinition(
        code="action:audit:read",
        name="查看操作日志",
        type="action",
        description="查看登录日志和操作日志。",
    ),
    PermissionDefinition(
        code="action:dictionaries:read",
        name="查看配置字典",
        type="action",
        description="查看字典类型和字典项。",
    ),
    PermissionDefinition(
        code="action:dictionaries:create",
        name="创建配置字典",
        type="action",
        description="创建字典类型和字典项。",
    ),
    PermissionDefinition(
        code="action:dictionaries:update",
        name="编辑配置字典",
        type="action",
        description="更新或删除字典项。",
    ),
    PermissionDefinition(
        code="action:files:read",
        name="查看文件资源",
        type="action",
        description="查看文件资源元数据。",
    ),
    PermissionDefinition(
        code="action:files:create",
        name="创建文件资源",
        type="action",
        description="创建文件资源元数据并上传文件内容。",
    ),
    PermissionDefinition(
        code=PERMISSION_MANAGE_SUPERUSER,
        name="管理超级用户状态",
        type="action",
        description="允许创建或更新拥有超级用户权限的账号。",
    ),
)
