export const uiCopy = {
  modules: {
    dashboard: "首页",
    knowledge: "知识库",
    documents: "文档中心",
    ragChat: "知识问答",
    apps: "应用中心",
    users: "用户管理",
    roles: "角色权限",
    departments: "空间管理",
    audit: "操作日志",
    dictionaries: "配置字典",
    files: "文件资源",
  },
  common: {
    actions: "操作",
    active: "启用",
    inactive: "停用",
    assigned: "已分配",
    unassigned: "未分配",
    cancel: "取消",
    code: "编码",
    create: "创建",
    delete: "删除",
    description: "描述",
    disable: "停用",
    download: "下载",
    edit: "编辑",
    email: "邮箱",
    enable: "启用",
    export: "导出",
    name: "名称",
    next: "下一页",
    no: "否",
    previous: "上一页",
    save: "保存",
    search: "搜索",
    status: "状态",
    system: "系统",
    upload: "上传",
    yes: "是",
  },
  fields: {
    admin: "管理员",
    department: "空间",
    departmentId: "空间编号",
    fullName: "姓名",
    initialPassword: "初始密码",
    newPassword: "新密码",
    password: "密码",
    roleCode: "角色编码",
    username: "用户名",
  },
  pagination: {
    selectedCount: (count: number) => `已选择 ${count} 个`,
  },
  empty: {
    apps: "暂无应用。",
    knowledgeBases: "暂无知识库。",
    documents: "暂无知识文档。",
    citations: "暂无引用来源。",
    departments: "暂无空间。",
    dictionaryItems: "暂无字典项。",
    dictionaryTypes: "暂无字典类型。",
    files: "暂无文件。",
    loginLogs: "暂无登录日志。",
    operationLogs: "暂无操作日志。",
    permissions: "没有匹配的权限。",
    roles: "暂无角色。",
    users: "暂无用户。",
  },
  status: {
    indexed: "已索引",
    failed: "失败",
    uploaded: "待索引",
  },
  errors: {
    loadApps: "无法加载应用。",
    loadKnowledgeBases: "无法加载知识库。",
    loadDocuments: "无法加载知识文档。",
    loadDepartments: "无法加载空间。",
    loadLoginLogs: "无法加载登录日志。",
    loadOperationLogs: "无法加载操作日志。",
    loadRoles: "无法加载角色。",
    loadUsers: "无法加载用户。",
  },
} as const;
