export const uiCopy = {
  modules: {
    dashboard: "仪表盘",
    users: "用户管理",
    roles: "角色管理",
    departments: "部门管理",
    audit: "审计日志",
    dictionaries: "字典管理",
    files: "文件管理",
  },
  common: {
    actions: "操作",
    active: "启用",
    inactive: "停用",
    assigned: "已分配",
    unassigned: "未分配",
    cancel: "取消",
    code: "编码",
    create: "创建",
    delete: "删除",
    description: "描述",
    disable: "停用",
    download: "下载",
    edit: "编辑",
    email: "邮箱",
    enable: "启用",
    export: "导出",
    name: "名称",
    next: "下一页",
    no: "否",
    previous: "上一页",
    save: "保存",
    search: "搜索",
    status: "状态",
    system: "系统",
    upload: "上传",
    yes: "是",
  },
  fields: {
    admin: "管理员",
    department: "部门",
    departmentId: "部门 ID",
    fullName: "姓名",
    initialPassword: "初始密码",
    newPassword: "新密码",
    password: "密码",
    roleCode: "角色编码",
    username: "用户名",
  },
  pagination: {
    selectedCount: (count: number) => `已选择 ${count} 个`,
  },
  empty: {
    departments: "暂无部门。",
    dictionaryItems: "暂无字典项。",
    dictionaryTypes: "暂无字典类型。",
    files: "暂无文件。",
    loginLogs: "暂无登录日志。",
    operationLogs: "暂无操作日志。",
    permissions: "没有匹配的权限。",
    roles: "暂无角色。",
    users: "暂无用户。",
  },
  errors: {
    loadDepartments: "无法加载部门。",
    loadLoginLogs: "无法加载登录日志。",
    loadOperationLogs: "无法加载操作日志。",
    loadRoles: "无法加载角色。",
    loadUsers: "无法加载用户。",
  },
} as const;
